### ISSUE TITLE
Karma values are ordered unintuitively

### ISSUE THREAD

**Issue by kparal** [blaskovic/fedora-gooey-karma#22]
When sending a karma value, I scroll the mouse wheel up on the karma drop-down list to select +1 karma. But I receive -1 karma instead. That is very weird. Direction up should be connected with positive values, and direction down with the negative values, don't you think?

![screenshot_001](https://f.cloud.github.com/assets/755451/975154/139b14a0-0670-11e3-8239-b41239bbcaf5.png)

Please re-order from
```
-1
0
+1
```
to
```
+1
0
-1
```

Also, please consider using radio buttons instead of the drop-down list. It's easier to click once than to click twice to select the value. Also, it could be some nice buttons (big ones, to hit them easily) with emoticon faces on them.

![screenshot_001 kopie](https://f.cloud.github.com/assets/755451/975170/5ed69aca-0670-11e3-8b27-0a058f73b3c9.png)

By default, no karma value should be selected, that will make sure the user won't forget the change the value from the previous update.

**Comment by blaskovic** [comment]
This should be fixed with the newest merged pull request.
